[mesa] Dont' remove virtual/libgbm
ERROR: Nothing PROVIDES 'virtual/nativesdk-libgbm' (but virtual:nativesdk:/home/hains/wrynose/openpli-oe-core/
openembedded-core/meta/recipes-graphics/virglrenderer/virglrenderer_1.2.0.bb DEPENDS on or otherwise requires it).