[ofgwrite] Fix build with security flag enabled
Introduced with:
https://github.com/openembedded/openembedded-core/commit/4c2d64c10a5b0437ab1ea04df22386f0f95124d1

Fix:

busybox/libbb/xfuncs_printf.c: In function 'malloc_or_warn':
| busybox/libbb/xfuncs_printf.c:40:30: error: format not a string literal and no format arguments [-Werror=format-security]
|    40 |                 bb_error_msg(bb_msg_memory_exhausted);
|       |                              ^~~~~~~~~~~~~~~~~~~~~~~
| busybox/libbb/xfuncs_printf.c: In function 'xmalloc':
| busybox/libbb/xfuncs_printf.c:49:38: error: format not a string literal and no format arguments [-Werror=format-security]
|    49 |                 bb_error_msg_and_die(bb_msg_memory_exhausted);
|       |                                      ^~~~~~~~~~~~~~~~~~~~~~~