[streamproxy] Suppress unused-result errors
| ../../sources/streamproxy-2+git/src/clientsocket.cpp: In constructor
            'ClientSocket::ClientSocket(int, default_streaming_action, const ConfigMap&, const stb_traits_t&)':
| ../../sources/streamproxy-2+git/src/clientsocket.cpp:389:30:
error: ignoring return value of 'ssize_t write(int, const void*, size_t)' declared with attribute
          'warn_unused_result' [-Werror=unused-result]
|   389 |                         write(fd, reply.c_str(), reply.length());
|       |                         ~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
| ../../sources/streamproxy-2+git/src/clientsocket.cpp:494:22: error: ignoring return value of
        'ssize_t write(int, const void*, size_t)' declared with attribute 'warn_unused_result' [-Werror=unused-result]
|   494 |                 write(fd, reply.c_str(), reply.length());
|       |                 ~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~