[openpli-common.conf] Drop ${DISTRO_FEATURES_LIBC} from DISTRO_FEATURES
See:
https://git.openembedded.org/openembedded-core/commit/?id=c62b1cc06613a4cdddf53290e6203559f43fc62d

Fix:

ERROR: Nothing PROVIDES 'nativesdk-gobject-introspection' (but virtual:nativesdk:/home/hains/wrynose/openpli-oe-core/
openembedded-core/meta/recipes-core/glib-2.0/glib-2.0_2.88.0.bb DEPENDS on or otherwise requires it).

After:
https://github.com/openembedded/openembedded-core/commit/6b553a5042b9d5828a9da675ede16e10f06dae90