[tzdata] Don't remove tzdata-posix
ERROR: Nothing RPROVIDES 'tzdata-posix' (but /home/hains/wrynose/openpli-oe-core/openembedded-core/
meta/recipes-core/glib-2.0/glib-2.0_2.88.0.bb RDEPENDS on or otherwise requires it)