[wsdd] Fix unused-result error
 wsdd.c: In function 'readSmbConf':
| wsdd.c:206:17: error: ignoring return value of 'fgets' declared with attribute 'warn_unused_result' [-Werror=unused-result]
|   206 |                 fgets(cd_name, sizeof(cd_name)-1, fp);
|       |                 ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
| wsdd.c:217:17: error: ignoring return value of 'fgets' declared with attribute 'warn_unused_result' [-Werror=unused-result]
|   217 |                 fgets(cd_workgroup, sizeof(cd_workgroup)-1, fp);
|       |                 ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~