[mpd] Update to 0.24.9 from meta-openembedded
To fix error:

| In file included from ../sources/mpd-0.24.6/src/io/Open.cxx:12:
| ../sources/mpd-0.24.6/src/system/linux/openat2.h:13:1: error:
 'int openat2(int, const char*, const open_how*, size_t)' redeclared inline without 'gnu_inline' attribute
|    13 | openat2(int dirfd, const char *pathname,
|       | ^~~~~~~