[openpli-common.conf] Drop opengl from DISTRO_FEATURES_DEFAULTS
Fix:

ERROR: Nothing PROVIDES 'virtual/egl' (but /home/hains/wrynose/openpli-oe-core/openembedded-core/
meta/recipes-gnome/gtk+/gtk4_4.22.1.bb DEPENDS on or otherwise requires it

Introduced with:
https://github.com/openembedded/openembedded-core/commit/2e1e7c86064ce36580953650b27cca9ae7c269c4