[miraclebox-blindscan-utils-mbmicro] Suppress no providers found in RDEPENDS error
ERROR: miraclebox-blindscan-utils-mbmicro-1.0-r1 do_package_qa: QA Issue: /usr/bin/ceryon-tda1002x contained in package
miraclebox-blindscan-dvbc-utils-mbmicro requires libxml2.so.2, but no providers found in RDEPENDS:miraclebox-blindscan-dvbc-utils-mbmicro? [file-rdeps]