vuplus-enigma2-package: Fix fetch error
ERROR: vuplus-enigma2-packages-experimental-git-r6 do_unpack: Bitbake Fetcher Error: UnpackError('No up to date source found:
clone directory not available or not up to date: /home/hains/whinlatter/openpli-oe-core/sources/git2/code.vuplus.com.git.dvbapp.git;
shallow clone not available: /home/hains/whinlatter/openpli-oe-core/sources/
gitshallow_code.vuplus.com.git.dvbapp.git_b0fb252-1_refs.tags.b0fb2521cedeac8089de73c3b59fd15bda0e99e0_vuplus_experimental.tar.gz',
 'git://code.vuplus.com/git/dvbapp.git;protocol=http;branch=vuplus_experimental;tag=b0fb2521cedeac8089de73c3b59fd15bda0e99e0')

To do: Update to latest git revision and update patches.